[book]
authors = ["Alloy Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Alloy Book"
description = "A book on all things Alloy"

[build]
create-missing = false

[preprocessor.external-links]

[output.html]
git-repository-url = "https://github.com/alloy-rs/book"
edit-url-template = "https://github.com/alloy-rs/book/edit/main/{path}"
default-theme = "ayu"

[output.html.fold]
enable = true
level = 0

[output.linkcheck]
